before_script:
  - node -v

cache:
  key: "PIPELINE-$CI_PIPELINE_ID"
  paths:
    - node_modules

prepare:
  script:
  - npm install --progress=false

lint:
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    when: on_success
    paths:
      - dist

test:
  script:
    - npm run test

stages:
  - prepare
  - lint
  - build
  - test
